#!/usr/bin/env bash
# Build the two-page CV the aviation-sector home page serves.
#
# Source of record (private, in the career notes):
#   ~/notes/morningpages/career/applications/outreach/cv_aviation_full.md
# This script never edits content: it runs that markdown through the career CV generator
# (tools/cv_print_html.py: same design head as every other CV, same public substitutions that
# anonymise the client), writes cv-en-full.src.html (excluded from the Jekyll build) and renders
# assets/Gabriel-Schutz-CV-EN-full.pdf (sub-labels and headings keep with the next block), then repeats the watcher's guards: 2 pages Letter, text
# layer, retired-claim grep, no client name, no phone number.
# The CV auto-publish watcher never touches these two files; committing and pushing is yours.
set -euo pipefail
cd "$(dirname "$0")/.."
CAREER="$HOME/notes/morningpages/career"
MD="$CAREER/applications/outreach/cv_aviation_full.md"
SRC="cv-en-full.src.html"
PDF="assets/Gabriel-Schutz-CV-EN-full.pdf"
PAGES=2

[[ -f "$MD" ]] || { echo "missing $MD"; exit 1; }
python3 - "$CAREER/tools" "$MD" "$SRC" <<'PY'
import sys
tools, md_path, out = sys.argv[1:]
sys.path.insert(0, tools)
import cv_print_html as g
md = open(md_path, encoding="utf-8").read()
html = ("<!DOCTYPE html>\n<!-- GENERATED by variants/render_cv.sh from the career CV master; do not edit by hand. -->\n"
        + g.HEAD.replace("</style>", "  h2, h3, p.keep { break-after: avoid; }\n</style>")
        + g.public_body(md).replace("<p><b>", '<p class="keep"><b>'))
open(out, "w", encoding="utf-8").write(html)
PY

google-chrome-stable --headless --disable-gpu --no-first-run --user-data-dir=/tmp/chrome-cv-site-full \
  --no-pdf-header-footer --print-to-pdf="$PDF" "$SRC" >/dev/null 2>&1

text="$(pdftotext "$PDF" - | tr '\n' ' ')"
pages="$(pdfinfo "$PDF" | awk '/^Pages:/{print $2}')"
bad=()
[[ "$pages" == "$PAGES" ]] || bad+=("$pages pages, expected $PAGES")
grep -q "Gabriel Sch" <<<"$text" || bad+=("text layer broken")
hits="$(grep -oiE 'co-led|brought in and managed|soup-to-nuts|639 rout|7[.,]4m|force index|1[.,]281|runc|sysbox|78 ?s ?(→|->) ?20|async invoicing|customer number|2028|camt\.052|36k-row|36[.,]?000[ -](rows|records)|17 days stale|accidentally deleted|\.NET|azure|airport[ -]fee|founded|relocation|60k' <<<"$text" | sort -u | tr '\n' ' ' || true)"
[[ -z "$hits" ]] || bad+=("retired/forbidden claim(s): $hits")
pub="$(grep -oE '\bDFS\b|\bDAS\b|\+55' <<<"$text" | sort -u | tr '\n' ' ' || true)"
[[ -z "$pub" ]] || bad+=("public render leaks: $pub")
if ((${#bad[@]})); then printf 'render_cv: FAILED: %s\n' "${bad[@]}"; exit 1; fi
echo "render_cv: $PDF  ${pages}p  $(stat -c%s "$PDF") bytes  deny-grep clean, client anonymised, no phone"
