#!/usr/bin/env bash
# Build the aviation-leaning CV the Vector-focused home page serves.
#
# Source of record: the founder-outreach aviation-fee CV
#   ~/notes/morningpages/career/applications/outreach/cv_aviation_fee.md  (edit THAT, then
#   `python3 tools/outreach_cv_render.py` from the career root, then re-run this script).
# This script never edits content by hand: it copies the outreach print source and applies the
# two public substitutions the site already uses for the payments CV:
#   1. the client is anonymised: "DFS Aviation Services (DAS)" -> "a national air-navigation services provider"
#   2. the phone number is dropped (public page)
# then renders cv-en-aviation.src.html -> assets/Gabriel-Schutz-CV-EN-aviation.pdf and repeats the
# watcher's guards (1 page Letter, text layer, retired-claim grep, no client name, no .NET).
# The CV auto-publish watcher never touches these two files; committing and pushing is yours.
set -euo pipefail
cd "$(dirname "$0")/.."
SRC_OUTREACH="$HOME/notes/morningpages/career/applications/outreach/Gabriel_Schutz_CV_EN.print.html"
SRC="cv-en-aviation.src.html"
PDF="assets/Gabriel-Schutz-CV-EN-aviation.pdf"
PAGES=1

[[ -f "$SRC_OUTREACH" ]] || { echo "missing $SRC_OUTREACH"; exit 1; }
python3 - "$SRC_OUTREACH" "$SRC" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
s = open(src, encoding="utf-8").read()
subs = [
  ("for the DFS Aviation Services (DAS) contract", "for a national air-navigation services provider"),
  (" &middot; +55 51 99469 4448", ""),
]
for old, new in subs:
    assert s.count(old) == 1, f"expected exactly one occurrence of {old!r} in the outreach source"
    s = s.replace(old, new)
s = re.sub(r"<!--.*?-->\s*", "", s, count=1, flags=re.S)  # the outreach header comment
s = ("<!-- GENERATED by variants/render_cv.sh from the founder-outreach aviation-fee CV\n"
     "     (career/applications/outreach/Gabriel_Schutz_CV_EN.print.html) with the public substitutions.\n"
     "     Do not edit by hand; edit cv_aviation_fee.md there and re-run the script. -->\n") + s
open(dst, "w", encoding="utf-8").write(s)
PY

google-chrome-stable --headless --disable-gpu --no-first-run --user-data-dir=/tmp/chrome-cv-site-aviation \
  --no-pdf-header-footer --print-to-pdf="$PDF" "$SRC" >/dev/null 2>&1

text="$(pdftotext "$PDF" - | tr '\n' ' ')"
pages="$(pdfinfo "$PDF" | awk '/^Pages:/{print $2}')"
bad=()
[[ "$pages" == "$PAGES" ]] || bad+=("$pages pages, expected $PAGES")
grep -q "Gabriel Sch" <<<"$text" || bad+=("text layer broken")
hits="$(grep -oiE 'co-led|brought in and managed|soup-to-nuts|639 rout|7[.,]4m|force index|1[.,]281|runc|sysbox|78 ?s ?(→|->) ?20|async invoicing|customer number|2028|camt\.052|36k-row|36[.,]?000[ -](rows|records)|17 days stale|accidentally deleted|\.NET|airport[ -]fee|founded|relocation' <<<"$text" | sort -u | tr '\n' ' ' || true)"
[[ -z "$hits" ]] || bad+=("retired/forbidden claim(s): $hits")
pub="$(grep -oE '\bDFS\b|\bDAS\b|\+55' <<<"$text" | sort -u | tr '\n' ' ' || true)"
[[ -z "$pub" ]] || bad+=("public render leaks: $pub")
if ((${#bad[@]})); then printf 'render_cv: FAILED: %s\n' "${bad[@]}"; exit 1; fi
echo "render_cv: $PDF  ${pages}p  $(stat -c%s "$PDF") bytes  deny-grep clean, client anonymised, no phone"
